hoten=input('Ho ten: ')
a=float(input('So ngay cong: '))
b=float(input('Don gia ngay cong: '))
c=float(input('He so phu cap: '))
d=float(input('Tam ung: '))
print('Nhan vien '+hoten+', Co tien Luong='+str(float(b*a*c))+', Tam ung='+str(d)+' va Thuc linh='+str(float(b*a*c-d)))